ERROR 00:00:21.276 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
INFO  00:00:31.592 c.t.s.c.adaptor.ClickatellAdaptor - Checking for expired ReplyIdReservations
ERROR 00:00:31.619 c.t.s.c.adaptor.ClickatellAdaptor - Failed to clean up expired ReplyIdReservations
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:293) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.makeConnection(Driver.java:393) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.connect(Driver.java:267) ~[postgresql-9.1-901.jdbc4.jar:na]
	at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_79]
	at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[na:1.7.0_79]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:98) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:324) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:319) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:138) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:685) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:215) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:542) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.4.1.v20121003-ad44345): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:602) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:186) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:278) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:304) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:282) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor.cleanupExpiredReplyIds(ClickatellAdaptor.java:595) ~[gsm-sms-adaptor-1.1.jar:na]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor$1.run(ClickatellAdaptor.java:1476) [gsm-sms-adaptor-1.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:00:45.595 c.t.i.j.s.s.i.PublishLaterRequestHandler - Transaction failed, failed to process PublishLaterRequestEntry
java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_79]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_79]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToSocketAddress(TcpEndpoint.java:678) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToHost(TcpEndpoint.java:608) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connect(TcpEndpoint.java:543) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager.connect(ConnectionManager.java:242) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager$ReqIterator.next(ConnectionManager.java:664) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicObjectEndpoint$1.next(BasicObjectEndpoint.java:370) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:708) ~[jsk-platform-2.2.1.jar:2.2.0]
Wrapped by: java.rmi.ConnectException: connection refused or timed out to BasicObjectEndpoint[65bf4513-5310-4fe4-af44-3fa956271998,TcpEndpoint[10.1.101.186:32817]]; nested exception is: 
	java.net.ConnectException: Connection timed out
	at net.jini.jeri.BasicInvocationHandler.wrapSafeIOException(BasicInvocationHandler.java:890) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:711) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethod(BasicInvocationHandler.java:659) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invoke(BasicInvocationHandler.java:528) ~[jsk-platform-2.2.1.jar:2.2.0]
	at com.sun.proxy.$Proxy466.createNewTransaction(Unknown Source) ~[na:na]
	at com.travellinck.infrastructure.jini.space.scheduling.impl.PublishLaterRequestHandler$2.call(PublishLaterRequestHandler.java:117) ~[approval-engine-components-1.1.10.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:00:47.283 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:01:10.730 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:01:36.751 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:02:02.853 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:02:28.756 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
INFO  00:02:31.620 c.t.s.c.adaptor.ClickatellAdaptor - Checking for expired ReplyIdReservations
ERROR 00:02:31.641 c.t.s.c.adaptor.ClickatellAdaptor - Failed to clean up expired ReplyIdReservations
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:293) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.makeConnection(Driver.java:393) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.connect(Driver.java:267) ~[postgresql-9.1-901.jdbc4.jar:na]
	at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_79]
	at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[na:1.7.0_79]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:98) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:324) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:319) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:138) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:685) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:215) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:542) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.4.1.v20121003-ad44345): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:602) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:186) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:278) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:304) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:282) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor.cleanupExpiredReplyIds(ClickatellAdaptor.java:595) ~[gsm-sms-adaptor-1.1.jar:na]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor$1.run(ClickatellAdaptor.java:1476) [gsm-sms-adaptor-1.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:02:54.253 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:02:56.664 c.t.i.j.s.s.i.PublishLaterRequestHandler - Transaction failed, failed to process PublishLaterRequestEntry
java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_79]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_79]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToSocketAddress(TcpEndpoint.java:678) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToHost(TcpEndpoint.java:608) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connect(TcpEndpoint.java:543) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager.connect(ConnectionManager.java:242) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager$ReqIterator.next(ConnectionManager.java:664) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicObjectEndpoint$1.next(BasicObjectEndpoint.java:370) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:708) ~[jsk-platform-2.2.1.jar:2.2.0]
Wrapped by: java.rmi.ConnectException: connection refused or timed out to BasicObjectEndpoint[65bf4513-5310-4fe4-af44-3fa956271998,TcpEndpoint[10.1.101.186:32817]]; nested exception is: 
	java.net.ConnectException: Connection timed out
	at net.jini.jeri.BasicInvocationHandler.wrapSafeIOException(BasicInvocationHandler.java:890) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:711) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethod(BasicInvocationHandler.java:659) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invoke(BasicInvocationHandler.java:528) ~[jsk-platform-2.2.1.jar:2.2.0]
	at com.sun.proxy.$Proxy466.createNewTransaction(Unknown Source) ~[na:na]
	at com.travellinck.infrastructure.jini.space.scheduling.impl.PublishLaterRequestHandler$2.call(PublishLaterRequestHandler.java:117) ~[approval-engine-components-1.1.10.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:03:19.641 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:03:44.626 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:04:10.403 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
INFO  00:04:31.641 c.t.s.c.adaptor.ClickatellAdaptor - Checking for expired ReplyIdReservations
ERROR 00:04:31.664 c.t.s.c.adaptor.ClickatellAdaptor - Failed to clean up expired ReplyIdReservations
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:293) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.makeConnection(Driver.java:393) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.connect(Driver.java:267) ~[postgresql-9.1-901.jdbc4.jar:na]
	at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_79]
	at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[na:1.7.0_79]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:98) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:324) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:319) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:138) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:685) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:215) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:542) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.4.1.v20121003-ad44345): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:602) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:186) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:278) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:304) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:282) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor.cleanupExpiredReplyIds(ClickatellAdaptor.java:595) ~[gsm-sms-adaptor-1.1.jar:na]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor$1.run(ClickatellAdaptor.java:1476) [gsm-sms-adaptor-1.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:04:36.027 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:05:01.625 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:05:07.738 c.t.i.j.s.s.i.PublishLaterRequestHandler - Transaction failed, failed to process PublishLaterRequestEntry
java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_79]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_79]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToSocketAddress(TcpEndpoint.java:678) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToHost(TcpEndpoint.java:608) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connect(TcpEndpoint.java:543) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager.connect(ConnectionManager.java:242) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager$ReqIterator.next(ConnectionManager.java:664) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicObjectEndpoint$1.next(BasicObjectEndpoint.java:370) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:708) ~[jsk-platform-2.2.1.jar:2.2.0]
Wrapped by: java.rmi.ConnectException: connection refused or timed out to BasicObjectEndpoint[65bf4513-5310-4fe4-af44-3fa956271998,TcpEndpoint[10.1.101.186:32817]]; nested exception is: 
	java.net.ConnectException: Connection timed out
	at net.jini.jeri.BasicInvocationHandler.wrapSafeIOException(BasicInvocationHandler.java:890) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:711) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethod(BasicInvocationHandler.java:659) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invoke(BasicInvocationHandler.java:528) ~[jsk-platform-2.2.1.jar:2.2.0]
	at com.sun.proxy.$Proxy466.createNewTransaction(Unknown Source) ~[na:na]
	at com.travellinck.infrastructure.jini.space.scheduling.impl.PublishLaterRequestHandler$2.call(PublishLaterRequestHandler.java:117) ~[approval-engine-components-1.1.10.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:05:24.152 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:05:48.129 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:06:15.376 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
INFO  00:06:31.680 c.t.s.c.adaptor.ClickatellAdaptor - Checking for expired ReplyIdReservations
ERROR 00:06:31.703 c.t.s.c.adaptor.ClickatellAdaptor - Failed to clean up expired ReplyIdReservations
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:293) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.makeConnection(Driver.java:393) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.connect(Driver.java:267) ~[postgresql-9.1-901.jdbc4.jar:na]
	at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_79]
	at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[na:1.7.0_79]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:98) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:324) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:319) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:138) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:685) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:215) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:542) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.4.1.v20121003-ad44345): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:602) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:186) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:278) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:304) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:282) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor.cleanupExpiredReplyIds(ClickatellAdaptor.java:595) ~[gsm-sms-adaptor-1.1.jar:na]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor$1.run(ClickatellAdaptor.java:1476) [gsm-sms-adaptor-1.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:06:41.971 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:07:08.492 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:07:18.812 c.t.i.j.s.s.i.PublishLaterRequestHandler - Transaction failed, failed to process PublishLaterRequestEntry
java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_79]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_79]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToSocketAddress(TcpEndpoint.java:678) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToHost(TcpEndpoint.java:608) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connect(TcpEndpoint.java:543) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager.connect(ConnectionManager.java:242) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager$ReqIterator.next(ConnectionManager.java:664) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicObjectEndpoint$1.next(BasicObjectEndpoint.java:370) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:708) ~[jsk-platform-2.2.1.jar:2.2.0]
Wrapped by: java.rmi.ConnectException: connection refused or timed out to BasicObjectEndpoint[65bf4513-5310-4fe4-af44-3fa956271998,TcpEndpoint[10.1.101.186:32817]]; nested exception is: 
	java.net.ConnectException: Connection timed out
	at net.jini.jeri.BasicInvocationHandler.wrapSafeIOException(BasicInvocationHandler.java:890) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:711) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethod(BasicInvocationHandler.java:659) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invoke(BasicInvocationHandler.java:528) ~[jsk-platform-2.2.1.jar:2.2.0]
	at com.sun.proxy.$Proxy466.createNewTransaction(Unknown Source) ~[na:na]
	at com.travellinck.infrastructure.jini.space.scheduling.impl.PublishLaterRequestHandler$2.call(PublishLaterRequestHandler.java:117) ~[approval-engine-components-1.1.10.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:07:31.838 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:07:57.437 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:08:20.065 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
INFO  00:08:31.704 c.t.s.c.adaptor.ClickatellAdaptor - Checking for expired ReplyIdReservations
ERROR 00:08:31.723 c.t.s.c.adaptor.ClickatellAdaptor - Failed to clean up expired ReplyIdReservations
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:293) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.makeConnection(Driver.java:393) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.connect(Driver.java:267) ~[postgresql-9.1-901.jdbc4.jar:na]
	at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_79]
	at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[na:1.7.0_79]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:98) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:324) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:319) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:138) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:685) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:215) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:542) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.4.1.v20121003-ad44345): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:602) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:186) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:278) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:304) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:282) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor.cleanupExpiredReplyIds(ClickatellAdaptor.java:595) ~[gsm-sms-adaptor-1.1.jar:na]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor$1.run(ClickatellAdaptor.java:1476) [gsm-sms-adaptor-1.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:08:42.080 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:09:08.122 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:09:33.978 c.t.i.j.s.s.i.PublishLaterRequestHandler - Transaction failed, failed to process PublishLaterRequestEntry
java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_79]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_79]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToSocketAddress(TcpEndpoint.java:678) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToHost(TcpEndpoint.java:608) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connect(TcpEndpoint.java:543) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager.connect(ConnectionManager.java:242) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager$ReqIterator.next(ConnectionManager.java:664) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicObjectEndpoint$1.next(BasicObjectEndpoint.java:370) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:708) ~[jsk-platform-2.2.1.jar:2.2.0]
Wrapped by: java.rmi.ConnectException: connection refused or timed out to BasicObjectEndpoint[65bf4513-5310-4fe4-af44-3fa956271998,TcpEndpoint[10.1.101.186:32817]]; nested exception is: 
	java.net.ConnectException: Connection timed out
	at net.jini.jeri.BasicInvocationHandler.wrapSafeIOException(BasicInvocationHandler.java:890) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:711) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethod(BasicInvocationHandler.java:659) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invoke(BasicInvocationHandler.java:528) ~[jsk-platform-2.2.1.jar:2.2.0]
	at com.sun.proxy.$Proxy466.createNewTransaction(Unknown Source) ~[na:na]
	at com.travellinck.infrastructure.jini.space.scheduling.impl.PublishLaterRequestHandler$2.call(PublishLaterRequestHandler.java:117) ~[approval-engine-components-1.1.10.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:09:34.060 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:09:57.348 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:10:20.995 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
INFO  00:10:31.724 c.t.s.c.adaptor.ClickatellAdaptor - Checking for expired ReplyIdReservations
ERROR 00:10:31.752 c.t.s.c.adaptor.ClickatellAdaptor - Failed to clean up expired ReplyIdReservations
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:293) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.makeConnection(Driver.java:393) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.connect(Driver.java:267) ~[postgresql-9.1-901.jdbc4.jar:na]
	at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_79]
	at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[na:1.7.0_79]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:98) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:324) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:319) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:138) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:685) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:215) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:542) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.4.1.v20121003-ad44345): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:602) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:186) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:278) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:304) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:282) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor.cleanupExpiredReplyIds(ClickatellAdaptor.java:595) ~[gsm-sms-adaptor-1.1.jar:na]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor$1.run(ClickatellAdaptor.java:1476) [gsm-sms-adaptor-1.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:10:43.693 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:11:06.535 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:11:31.113 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:11:45.050 c.t.i.j.s.s.i.PublishLaterRequestHandler - Transaction failed, failed to process PublishLaterRequestEntry
java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_79]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_79]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToSocketAddress(TcpEndpoint.java:678) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToHost(TcpEndpoint.java:608) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connect(TcpEndpoint.java:543) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager.connect(ConnectionManager.java:242) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager$ReqIterator.next(ConnectionManager.java:664) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicObjectEndpoint$1.next(BasicObjectEndpoint.java:370) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:708) ~[jsk-platform-2.2.1.jar:2.2.0]
Wrapped by: java.rmi.ConnectException: connection refused or timed out to BasicObjectEndpoint[65bf4513-5310-4fe4-af44-3fa956271998,TcpEndpoint[10.1.101.186:32817]]; nested exception is: 
	java.net.ConnectException: Connection timed out
	at net.jini.jeri.BasicInvocationHandler.wrapSafeIOException(BasicInvocationHandler.java:890) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:711) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethod(BasicInvocationHandler.java:659) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invoke(BasicInvocationHandler.java:528) ~[jsk-platform-2.2.1.jar:2.2.0]
	at com.sun.proxy.$Proxy466.createNewTransaction(Unknown Source) ~[na:na]
	at com.travellinck.infrastructure.jini.space.scheduling.impl.PublishLaterRequestHandler$2.call(PublishLaterRequestHandler.java:117) ~[approval-engine-components-1.1.10.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:11:56.325 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:12:23.767 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
INFO  00:12:31.753 c.t.s.c.adaptor.ClickatellAdaptor - Checking for expired ReplyIdReservations
ERROR 00:12:31.775 c.t.s.c.adaptor.ClickatellAdaptor - Failed to clean up expired ReplyIdReservations
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:293) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.makeConnection(Driver.java:393) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.connect(Driver.java:267) ~[postgresql-9.1-901.jdbc4.jar:na]
	at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_79]
	at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[na:1.7.0_79]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:98) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:324) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:319) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:138) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:685) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:215) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:542) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.4.1.v20121003-ad44345): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:602) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:186) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:278) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:304) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:282) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor.cleanupExpiredReplyIds(ClickatellAdaptor.java:595) ~[gsm-sms-adaptor-1.1.jar:na]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor$1.run(ClickatellAdaptor.java:1476) [gsm-sms-adaptor-1.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:12:49.376 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:13:15.990 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:13:41.896 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:13:56.122 c.t.i.j.s.s.i.PublishLaterRequestHandler - Transaction failed, failed to process PublishLaterRequestEntry
java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_79]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_79]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToSocketAddress(TcpEndpoint.java:678) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToHost(TcpEndpoint.java:608) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connect(TcpEndpoint.java:543) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager.connect(ConnectionManager.java:242) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager$ReqIterator.next(ConnectionManager.java:664) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicObjectEndpoint$1.next(BasicObjectEndpoint.java:370) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:708) ~[jsk-platform-2.2.1.jar:2.2.0]
Wrapped by: java.rmi.ConnectException: connection refused or timed out to BasicObjectEndpoint[65bf4513-5310-4fe4-af44-3fa956271998,TcpEndpoint[10.1.101.186:32817]]; nested exception is: 
	java.net.ConnectException: Connection timed out
	at net.jini.jeri.BasicInvocationHandler.wrapSafeIOException(BasicInvocationHandler.java:890) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:711) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethod(BasicInvocationHandler.java:659) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invoke(BasicInvocationHandler.java:528) ~[jsk-platform-2.2.1.jar:2.2.0]
	at com.sun.proxy.$Proxy466.createNewTransaction(Unknown Source) ~[na:na]
	at com.travellinck.infrastructure.jini.space.scheduling.impl.PublishLaterRequestHandler$2.call(PublishLaterRequestHandler.java:117) ~[approval-engine-components-1.1.10.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:14:05.243 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:14:31.456 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
INFO  00:14:31.776 c.t.s.c.adaptor.ClickatellAdaptor - Checking for expired ReplyIdReservations
ERROR 00:14:31.797 c.t.s.c.adaptor.ClickatellAdaptor - Failed to clean up expired ReplyIdReservations
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:293) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.makeConnection(Driver.java:393) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.connect(Driver.java:267) ~[postgresql-9.1-901.jdbc4.jar:na]
	at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_79]
	at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[na:1.7.0_79]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:98) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:324) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:319) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:138) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:685) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:215) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:542) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.4.1.v20121003-ad44345): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:602) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:186) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:278) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:304) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:282) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor.cleanupExpiredReplyIds(ClickatellAdaptor.java:595) ~[gsm-sms-adaptor-1.1.jar:na]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor$1.run(ClickatellAdaptor.java:1476) [gsm-sms-adaptor-1.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:14:55.007 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:15:20.197 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:15:46.309 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:16:07.194 c.t.i.j.s.s.i.PublishLaterRequestHandler - Transaction failed, failed to process PublishLaterRequestEntry
java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_79]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_79]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToSocketAddress(TcpEndpoint.java:678) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToHost(TcpEndpoint.java:608) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connect(TcpEndpoint.java:543) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager.connect(ConnectionManager.java:242) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager$ReqIterator.next(ConnectionManager.java:664) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicObjectEndpoint$1.next(BasicObjectEndpoint.java:370) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:708) ~[jsk-platform-2.2.1.jar:2.2.0]
Wrapped by: java.rmi.ConnectException: connection refused or timed out to BasicObjectEndpoint[65bf4513-5310-4fe4-af44-3fa956271998,TcpEndpoint[10.1.101.186:32817]]; nested exception is: 
	java.net.ConnectException: Connection timed out
	at net.jini.jeri.BasicInvocationHandler.wrapSafeIOException(BasicInvocationHandler.java:890) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:711) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethod(BasicInvocationHandler.java:659) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invoke(BasicInvocationHandler.java:528) ~[jsk-platform-2.2.1.jar:2.2.0]
	at com.sun.proxy.$Proxy466.createNewTransaction(Unknown Source) ~[na:na]
	at com.travellinck.infrastructure.jini.space.scheduling.impl.PublishLaterRequestHandler$2.call(PublishLaterRequestHandler.java:117) ~[approval-engine-components-1.1.10.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:16:13.852 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
INFO  00:16:31.798 c.t.s.c.adaptor.ClickatellAdaptor - Checking for expired ReplyIdReservations
ERROR 00:16:31.818 c.t.s.c.adaptor.ClickatellAdaptor - Failed to clean up expired ReplyIdReservations
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:293) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.makeConnection(Driver.java:393) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.connect(Driver.java:267) ~[postgresql-9.1-901.jdbc4.jar:na]
	at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_79]
	at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[na:1.7.0_79]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:98) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:324) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:319) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:138) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:685) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:215) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:542) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.4.1.v20121003-ad44345): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:602) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:186) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:278) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:304) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:282) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor.cleanupExpiredReplyIds(ClickatellAdaptor.java:595) ~[gsm-sms-adaptor-1.1.jar:na]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor$1.run(ClickatellAdaptor.java:1476) [gsm-sms-adaptor-1.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:16:37.706 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:17:03.516 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:17:29.115 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:17:54.407 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:18:19.085 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:18:22.364 c.t.i.j.s.s.i.PublishLaterRequestHandler - Transaction failed, failed to process PublishLaterRequestEntry
java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_79]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_79]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToSocketAddress(TcpEndpoint.java:678) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToHost(TcpEndpoint.java:608) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connect(TcpEndpoint.java:543) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager.connect(ConnectionManager.java:242) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager$ReqIterator.next(ConnectionManager.java:664) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicObjectEndpoint$1.next(BasicObjectEndpoint.java:370) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:708) ~[jsk-platform-2.2.1.jar:2.2.0]
Wrapped by: java.rmi.ConnectException: connection refused or timed out to BasicObjectEndpoint[65bf4513-5310-4fe4-af44-3fa956271998,TcpEndpoint[10.1.101.186:32817]]; nested exception is: 
	java.net.ConnectException: Connection timed out
	at net.jini.jeri.BasicInvocationHandler.wrapSafeIOException(BasicInvocationHandler.java:890) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:711) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethod(BasicInvocationHandler.java:659) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invoke(BasicInvocationHandler.java:528) ~[jsk-platform-2.2.1.jar:2.2.0]
	at com.sun.proxy.$Proxy466.createNewTransaction(Unknown Source) ~[na:na]
	at com.travellinck.infrastructure.jini.space.scheduling.impl.PublishLaterRequestHandler$2.call(PublishLaterRequestHandler.java:117) ~[approval-engine-components-1.1.10.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
INFO  00:18:31.819 c.t.s.c.adaptor.ClickatellAdaptor - Checking for expired ReplyIdReservations
ERROR 00:18:31.842 c.t.s.c.adaptor.ClickatellAdaptor - Failed to clean up expired ReplyIdReservations
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:293) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.makeConnection(Driver.java:393) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.connect(Driver.java:267) ~[postgresql-9.1-901.jdbc4.jar:na]
	at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_79]
	at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[na:1.7.0_79]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:98) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:324) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:319) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:138) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:685) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:215) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:542) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.4.1.v20121003-ad44345): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:602) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:186) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:278) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:304) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:282) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor.cleanupExpiredReplyIds(ClickatellAdaptor.java:595) ~[gsm-sms-adaptor-1.1.jar:na]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor$1.run(ClickatellAdaptor.java:1476) [gsm-sms-adaptor-1.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:18:44.695 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:19:11.205 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:19:34.449 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:20:00.049 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:20:23.395 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
INFO  00:20:31.842 c.t.s.c.adaptor.ClickatellAdaptor - Checking for expired ReplyIdReservations
ERROR 00:20:31.868 c.t.s.c.adaptor.ClickatellAdaptor - Failed to clean up expired ReplyIdReservations
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:293) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.makeConnection(Driver.java:393) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.connect(Driver.java:267) ~[postgresql-9.1-901.jdbc4.jar:na]
	at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_79]
	at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[na:1.7.0_79]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:98) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:324) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:319) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:138) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:685) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:215) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:542) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.4.1.v20121003-ad44345): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:602) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:186) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:278) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:304) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:282) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor.cleanupExpiredReplyIds(ClickatellAdaptor.java:595) ~[gsm-sms-adaptor-1.1.jar:na]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor$1.run(ClickatellAdaptor.java:1476) [gsm-sms-adaptor-1.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:20:33.433 c.t.i.j.s.s.i.PublishLaterRequestHandler - Transaction failed, failed to process PublishLaterRequestEntry
java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_79]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_79]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToSocketAddress(TcpEndpoint.java:678) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToHost(TcpEndpoint.java:608) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connect(TcpEndpoint.java:543) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager.connect(ConnectionManager.java:242) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager$ReqIterator.next(ConnectionManager.java:664) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicObjectEndpoint$1.next(BasicObjectEndpoint.java:370) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:708) ~[jsk-platform-2.2.1.jar:2.2.0]
Wrapped by: java.rmi.ConnectException: connection refused or timed out to BasicObjectEndpoint[65bf4513-5310-4fe4-af44-3fa956271998,TcpEndpoint[10.1.101.186:32817]]; nested exception is: 
	java.net.ConnectException: Connection timed out
	at net.jini.jeri.BasicInvocationHandler.wrapSafeIOException(BasicInvocationHandler.java:890) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:711) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethod(BasicInvocationHandler.java:659) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invoke(BasicInvocationHandler.java:528) ~[jsk-platform-2.2.1.jar:2.2.0]
	at com.sun.proxy.$Proxy466.createNewTransaction(Unknown Source) ~[na:na]
	at com.travellinck.infrastructure.jini.space.scheduling.impl.PublishLaterRequestHandler$2.call(PublishLaterRequestHandler.java:117) ~[approval-engine-components-1.1.10.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:20:48.995 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:21:12.239 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:21:35.279 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:22:01.902 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:22:28.218 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
INFO  00:22:31.869 c.t.s.c.adaptor.ClickatellAdaptor - Checking for expired ReplyIdReservations
ERROR 00:22:31.891 c.t.s.c.adaptor.ClickatellAdaptor - Failed to clean up expired ReplyIdReservations
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:293) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.makeConnection(Driver.java:393) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.connect(Driver.java:267) ~[postgresql-9.1-901.jdbc4.jar:na]
	at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_79]
	at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[na:1.7.0_79]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:98) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:324) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:319) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:138) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:685) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:215) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:542) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.4.1.v20121003-ad44345): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:602) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:186) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:278) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:304) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:282) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor.cleanupExpiredReplyIds(ClickatellAdaptor.java:595) ~[gsm-sms-adaptor-1.1.jar:na]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor$1.run(ClickatellAdaptor.java:1476) [gsm-sms-adaptor-1.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:22:44.507 c.t.i.j.s.s.i.PublishLaterRequestHandler - Transaction failed, failed to process PublishLaterRequestEntry
java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_79]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_79]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToSocketAddress(TcpEndpoint.java:678) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToHost(TcpEndpoint.java:608) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connect(TcpEndpoint.java:543) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager.connect(ConnectionManager.java:242) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager$ReqIterator.next(ConnectionManager.java:664) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicObjectEndpoint$1.next(BasicObjectEndpoint.java:370) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:708) ~[jsk-platform-2.2.1.jar:2.2.0]
Wrapped by: java.rmi.ConnectException: connection refused or timed out to BasicObjectEndpoint[65bf4513-5310-4fe4-af44-3fa956271998,TcpEndpoint[10.1.101.186:32817]]; nested exception is: 
	java.net.ConnectException: Connection timed out
	at net.jini.jeri.BasicInvocationHandler.wrapSafeIOException(BasicInvocationHandler.java:890) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:711) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethod(BasicInvocationHandler.java:659) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invoke(BasicInvocationHandler.java:528) ~[jsk-platform-2.2.1.jar:2.2.0]
	at com.sun.proxy.$Proxy466.createNewTransaction(Unknown Source) ~[na:na]
	at com.travellinck.infrastructure.jini.space.scheduling.impl.PublishLaterRequestHandler$2.call(PublishLaterRequestHandler.java:117) ~[approval-engine-components-1.1.10.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:22:55.604 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:23:21.875 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:23:47.987 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:24:12.971 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
INFO  00:24:31.892 c.t.s.c.adaptor.ClickatellAdaptor - Checking for expired ReplyIdReservations
ERROR 00:24:31.933 c.t.s.c.adaptor.ClickatellAdaptor - Failed to clean up expired ReplyIdReservations
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:293) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.makeConnection(Driver.java:393) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.connect(Driver.java:267) ~[postgresql-9.1-901.jdbc4.jar:na]
	at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_79]
	at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[na:1.7.0_79]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:98) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:324) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:319) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:138) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:685) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:215) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:542) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.4.1.v20121003-ad44345): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:602) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:186) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:278) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:304) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:282) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor.cleanupExpiredReplyIds(ClickatellAdaptor.java:595) ~[gsm-sms-adaptor-1.1.jar:na]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor$1.run(ClickatellAdaptor.java:1476) [gsm-sms-adaptor-1.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:24:39.492 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:24:55.587 c.t.i.j.s.s.i.PublishLaterRequestHandler - Transaction failed, failed to process PublishLaterRequestEntry
java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_79]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_79]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToSocketAddress(TcpEndpoint.java:678) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToHost(TcpEndpoint.java:608) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connect(TcpEndpoint.java:543) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager.connect(ConnectionManager.java:242) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager$ReqIterator.next(ConnectionManager.java:664) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicObjectEndpoint$1.next(BasicObjectEndpoint.java:370) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:708) ~[jsk-platform-2.2.1.jar:2.2.0]
Wrapped by: java.rmi.ConnectException: connection refused or timed out to BasicObjectEndpoint[65bf4513-5310-4fe4-af44-3fa956271998,TcpEndpoint[10.1.101.186:32817]]; nested exception is: 
	java.net.ConnectException: Connection timed out
	at net.jini.jeri.BasicInvocationHandler.wrapSafeIOException(BasicInvocationHandler.java:890) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:711) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethod(BasicInvocationHandler.java:659) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invoke(BasicInvocationHandler.java:528) ~[jsk-platform-2.2.1.jar:2.2.0]
	at com.sun.proxy.$Proxy466.createNewTransaction(Unknown Source) ~[na:na]
	at com.travellinck.infrastructure.jini.space.scheduling.impl.PublishLaterRequestHandler$2.call(PublishLaterRequestHandler.java:117) ~[approval-engine-components-1.1.10.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:25:05.399 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:25:29.053 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:25:54.959 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:26:21.788 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
INFO  00:26:31.934 c.t.s.c.adaptor.ClickatellAdaptor - Checking for expired ReplyIdReservations
ERROR 00:26:31.957 c.t.s.c.adaptor.ClickatellAdaptor - Failed to clean up expired ReplyIdReservations
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:293) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.makeConnection(Driver.java:393) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.connect(Driver.java:267) ~[postgresql-9.1-901.jdbc4.jar:na]
	at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_79]
	at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[na:1.7.0_79]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:98) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:324) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:319) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:138) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:685) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:215) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:542) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.4.1.v20121003-ad44345): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:602) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:186) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:278) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:304) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:282) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor.cleanupExpiredReplyIds(ClickatellAdaptor.java:595) ~[gsm-sms-adaptor-1.1.jar:na]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor$1.run(ClickatellAdaptor.java:1476) [gsm-sms-adaptor-1.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:26:44.827 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:27:10.444 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:27:10.748 c.t.i.j.s.s.i.PublishLaterRequestHandler - Transaction failed, failed to process PublishLaterRequestEntry
java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_79]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_79]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToSocketAddress(TcpEndpoint.java:678) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToHost(TcpEndpoint.java:608) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connect(TcpEndpoint.java:543) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager.connect(ConnectionManager.java:242) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager$ReqIterator.next(ConnectionManager.java:664) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicObjectEndpoint$1.next(BasicObjectEndpoint.java:370) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:708) ~[jsk-platform-2.2.1.jar:2.2.0]
Wrapped by: java.rmi.ConnectException: connection refused or timed out to BasicObjectEndpoint[65bf4513-5310-4fe4-af44-3fa956271998,TcpEndpoint[10.1.101.186:32817]]; nested exception is: 
	java.net.ConnectException: Connection timed out
	at net.jini.jeri.BasicInvocationHandler.wrapSafeIOException(BasicInvocationHandler.java:890) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:711) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethod(BasicInvocationHandler.java:659) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invoke(BasicInvocationHandler.java:528) ~[jsk-platform-2.2.1.jar:2.2.0]
	at com.sun.proxy.$Proxy466.createNewTransaction(Unknown Source) ~[na:na]
	at com.travellinck.infrastructure.jini.space.scheduling.impl.PublishLaterRequestHandler$2.call(PublishLaterRequestHandler.java:117) ~[approval-engine-components-1.1.10.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:27:35.527 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:28:01.541 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:28:28.785 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
INFO  00:28:31.958 c.t.s.c.adaptor.ClickatellAdaptor - Checking for expired ReplyIdReservations
ERROR 00:28:31.985 c.t.s.c.adaptor.ClickatellAdaptor - Failed to clean up expired ReplyIdReservations
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:293) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.makeConnection(Driver.java:393) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.connect(Driver.java:267) ~[postgresql-9.1-901.jdbc4.jar:na]
	at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_79]
	at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[na:1.7.0_79]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:98) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:324) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:319) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:138) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:685) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:215) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:542) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.4.1.v20121003-ad44345): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:602) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:186) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:278) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:304) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:282) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor.cleanupExpiredReplyIds(ClickatellAdaptor.java:595) ~[gsm-sms-adaptor-1.1.jar:na]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor$1.run(ClickatellAdaptor.java:1476) [gsm-sms-adaptor-1.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:28:52.649 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:29:18.663 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:29:21.814 c.t.i.j.s.s.i.PublishLaterRequestHandler - Transaction failed, failed to process PublishLaterRequestEntry
java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_79]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_79]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToSocketAddress(TcpEndpoint.java:678) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToHost(TcpEndpoint.java:608) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connect(TcpEndpoint.java:543) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager.connect(ConnectionManager.java:242) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager$ReqIterator.next(ConnectionManager.java:664) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicObjectEndpoint$1.next(BasicObjectEndpoint.java:370) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:708) ~[jsk-platform-2.2.1.jar:2.2.0]
Wrapped by: java.rmi.ConnectException: connection refused or timed out to BasicObjectEndpoint[65bf4513-5310-4fe4-af44-3fa956271998,TcpEndpoint[10.1.101.186:32817]]; nested exception is: 
	java.net.ConnectException: Connection timed out
	at net.jini.jeri.BasicInvocationHandler.wrapSafeIOException(BasicInvocationHandler.java:890) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:711) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethod(BasicInvocationHandler.java:659) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invoke(BasicInvocationHandler.java:528) ~[jsk-platform-2.2.1.jar:2.2.0]
	at com.sun.proxy.$Proxy466.createNewTransaction(Unknown Source) ~[na:na]
	at com.travellinck.infrastructure.jini.space.scheduling.impl.PublishLaterRequestHandler$2.call(PublishLaterRequestHandler.java:117) ~[approval-engine-components-1.1.10.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:29:42.629 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:30:08.642 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
INFO  00:30:31.986 c.t.s.c.adaptor.ClickatellAdaptor - Checking for expired ReplyIdReservations
ERROR 00:30:32.016 c.t.s.c.adaptor.ClickatellAdaptor - Failed to clean up expired ReplyIdReservations
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:293) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.makeConnection(Driver.java:393) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.connect(Driver.java:267) ~[postgresql-9.1-901.jdbc4.jar:na]
	at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_79]
	at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[na:1.7.0_79]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:98) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:324) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:319) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:138) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:685) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:215) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:542) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.4.1.v20121003-ad44345): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:602) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:186) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:278) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:304) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:282) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor.cleanupExpiredReplyIds(ClickatellAdaptor.java:595) ~[gsm-sms-adaptor-1.1.jar:na]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor$1.run(ClickatellAdaptor.java:1476) [gsm-sms-adaptor-1.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:30:33.939 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:30:59.952 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:31:25.761 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:31:32.892 c.t.i.j.s.s.i.PublishLaterRequestHandler - Transaction failed, failed to process PublishLaterRequestEntry
java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_79]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_79]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToSocketAddress(TcpEndpoint.java:678) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToHost(TcpEndpoint.java:608) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connect(TcpEndpoint.java:543) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager.connect(ConnectionManager.java:242) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager$ReqIterator.next(ConnectionManager.java:664) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicObjectEndpoint$1.next(BasicObjectEndpoint.java:370) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:708) ~[jsk-platform-2.2.1.jar:2.2.0]
Wrapped by: java.rmi.ConnectException: connection refused or timed out to BasicObjectEndpoint[65bf4513-5310-4fe4-af44-3fa956271998,TcpEndpoint[10.1.101.186:32817]]; nested exception is: 
	java.net.ConnectException: Connection timed out
	at net.jini.jeri.BasicInvocationHandler.wrapSafeIOException(BasicInvocationHandler.java:890) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:711) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethod(BasicInvocationHandler.java:659) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invoke(BasicInvocationHandler.java:528) ~[jsk-platform-2.2.1.jar:2.2.0]
	at com.sun.proxy.$Proxy466.createNewTransaction(Unknown Source) ~[na:na]
	at com.travellinck.infrastructure.jini.space.scheduling.impl.PublishLaterRequestHandler$2.call(PublishLaterRequestHandler.java:117) ~[approval-engine-components-1.1.10.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:31:51.672 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:32:16.891 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
INFO  00:32:32.017 c.t.s.c.adaptor.ClickatellAdaptor - Checking for expired ReplyIdReservations
ERROR 00:32:32.035 c.t.s.c.adaptor.ClickatellAdaptor - Failed to clean up expired ReplyIdReservations
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:293) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.makeConnection(Driver.java:393) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.connect(Driver.java:267) ~[postgresql-9.1-901.jdbc4.jar:na]
	at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_79]
	at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[na:1.7.0_79]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:98) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:324) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:319) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:138) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:685) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:215) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:542) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.4.1.v20121003-ad44345): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:602) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:186) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:278) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:304) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:282) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor.cleanupExpiredReplyIds(ClickatellAdaptor.java:595) ~[gsm-sms-adaptor-1.1.jar:na]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor$1.run(ClickatellAdaptor.java:1476) [gsm-sms-adaptor-1.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:32:43.186 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:33:09.193 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:33:33.265 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:33:43.961 c.t.i.j.s.s.i.PublishLaterRequestHandler - Transaction failed, failed to process PublishLaterRequestEntry
java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_79]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_79]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToSocketAddress(TcpEndpoint.java:678) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToHost(TcpEndpoint.java:608) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connect(TcpEndpoint.java:543) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager.connect(ConnectionManager.java:242) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager$ReqIterator.next(ConnectionManager.java:664) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicObjectEndpoint$1.next(BasicObjectEndpoint.java:370) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:708) ~[jsk-platform-2.2.1.jar:2.2.0]
Wrapped by: java.rmi.ConnectException: connection refused or timed out to BasicObjectEndpoint[65bf4513-5310-4fe4-af44-3fa956271998,TcpEndpoint[10.1.101.186:32817]]; nested exception is: 
	java.net.ConnectException: Connection timed out
	at net.jini.jeri.BasicInvocationHandler.wrapSafeIOException(BasicInvocationHandler.java:890) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:711) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethod(BasicInvocationHandler.java:659) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invoke(BasicInvocationHandler.java:528) ~[jsk-platform-2.2.1.jar:2.2.0]
	at com.sun.proxy.$Proxy466.createNewTransaction(Unknown Source) ~[na:na]
	at com.travellinck.infrastructure.jini.space.scheduling.impl.PublishLaterRequestHandler$2.call(PublishLaterRequestHandler.java:117) ~[approval-engine-components-1.1.10.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:33:58.766 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:34:24.369 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
INFO  00:34:32.038 c.t.s.c.adaptor.ClickatellAdaptor - Checking for expired ReplyIdReservations
ERROR 00:34:32.060 c.t.s.c.adaptor.ClickatellAdaptor - Failed to clean up expired ReplyIdReservations
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:293) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.makeConnection(Driver.java:393) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.connect(Driver.java:267) ~[postgresql-9.1-901.jdbc4.jar:na]
	at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_79]
	at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[na:1.7.0_79]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:98) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:324) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:319) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:138) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:685) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:215) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:542) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.4.1.v20121003-ad44345): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:602) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:186) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:278) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:304) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:282) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor.cleanupExpiredReplyIds(ClickatellAdaptor.java:595) ~[gsm-sms-adaptor-1.1.jar:na]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor$1.run(ClickatellAdaptor.java:1476) [gsm-sms-adaptor-1.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:34:48.230 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:35:13.731 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:35:37.291 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:35:59.127 c.t.i.j.s.s.i.PublishLaterRequestHandler - Transaction failed, failed to process PublishLaterRequestEntry
java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_79]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_79]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToSocketAddress(TcpEndpoint.java:678) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToHost(TcpEndpoint.java:608) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connect(TcpEndpoint.java:543) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager.connect(ConnectionManager.java:242) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager$ReqIterator.next(ConnectionManager.java:664) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicObjectEndpoint$1.next(BasicObjectEndpoint.java:370) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:708) ~[jsk-platform-2.2.1.jar:2.2.0]
Wrapped by: java.rmi.ConnectException: connection refused or timed out to BasicObjectEndpoint[65bf4513-5310-4fe4-af44-3fa956271998,TcpEndpoint[10.1.101.186:32817]]; nested exception is: 
	java.net.ConnectException: Connection timed out
	at net.jini.jeri.BasicInvocationHandler.wrapSafeIOException(BasicInvocationHandler.java:890) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:711) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethod(BasicInvocationHandler.java:659) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invoke(BasicInvocationHandler.java:528) ~[jsk-platform-2.2.1.jar:2.2.0]
	at com.sun.proxy.$Proxy466.createNewTransaction(Unknown Source) ~[na:na]
	at com.travellinck.infrastructure.jini.space.scheduling.impl.PublishLaterRequestHandler$2.call(PublishLaterRequestHandler.java:117) ~[approval-engine-components-1.1.10.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:36:02.785 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:36:29.103 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
INFO  00:36:32.061 c.t.s.c.adaptor.ClickatellAdaptor - Checking for expired ReplyIdReservations
ERROR 00:36:32.084 c.t.s.c.adaptor.ClickatellAdaptor - Failed to clean up expired ReplyIdReservations
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:293) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.makeConnection(Driver.java:393) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.connect(Driver.java:267) ~[postgresql-9.1-901.jdbc4.jar:na]
	at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_79]
	at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[na:1.7.0_79]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:98) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:324) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:319) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:138) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:685) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:215) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:542) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.4.1.v20121003-ad44345): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:602) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:186) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:278) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:304) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:282) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor.cleanupExpiredReplyIds(ClickatellAdaptor.java:595) ~[gsm-sms-adaptor-1.1.jar:na]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor$1.run(ClickatellAdaptor.java:1476) [gsm-sms-adaptor-1.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:36:52.760 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:37:17.645 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:37:43.657 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:38:07.006 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:38:10.204 c.t.i.j.s.s.i.PublishLaterRequestHandler - Transaction failed, failed to process PublishLaterRequestEntry
java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_79]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_79]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToSocketAddress(TcpEndpoint.java:678) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToHost(TcpEndpoint.java:608) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connect(TcpEndpoint.java:543) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager.connect(ConnectionManager.java:242) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager$ReqIterator.next(ConnectionManager.java:664) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicObjectEndpoint$1.next(BasicObjectEndpoint.java:370) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:708) ~[jsk-platform-2.2.1.jar:2.2.0]
Wrapped by: java.rmi.ConnectException: connection refused or timed out to BasicObjectEndpoint[65bf4513-5310-4fe4-af44-3fa956271998,TcpEndpoint[10.1.101.186:32817]]; nested exception is: 
	java.net.ConnectException: Connection timed out
	at net.jini.jeri.BasicInvocationHandler.wrapSafeIOException(BasicInvocationHandler.java:890) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:711) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethod(BasicInvocationHandler.java:659) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invoke(BasicInvocationHandler.java:528) ~[jsk-platform-2.2.1.jar:2.2.0]
	at com.sun.proxy.$Proxy466.createNewTransaction(Unknown Source) ~[na:na]
	at com.travellinck.infrastructure.jini.space.scheduling.impl.PublishLaterRequestHandler$2.call(PublishLaterRequestHandler.java:117) ~[approval-engine-components-1.1.10.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
INFO  00:38:32.085 c.t.s.c.adaptor.ClickatellAdaptor - Checking for expired ReplyIdReservations
ERROR 00:38:32.111 c.t.s.c.adaptor.ClickatellAdaptor - Failed to clean up expired ReplyIdReservations
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:293) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.makeConnection(Driver.java:393) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.connect(Driver.java:267) ~[postgresql-9.1-901.jdbc4.jar:na]
	at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_79]
	at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[na:1.7.0_79]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:98) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:324) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:319) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:138) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:685) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:215) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:542) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.4.1.v20121003-ad44345): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:602) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:186) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:278) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:304) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:282) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor.cleanupExpiredReplyIds(ClickatellAdaptor.java:595) ~[gsm-sms-adaptor-1.1.jar:na]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor$1.run(ClickatellAdaptor.java:1476) [gsm-sms-adaptor-1.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:38:32.300 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:38:57.288 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:39:21.252 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:39:48.184 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:40:13.786 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:40:21.273 c.t.i.j.s.s.i.PublishLaterRequestHandler - Transaction failed, failed to process PublishLaterRequestEntry
java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_79]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_79]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToSocketAddress(TcpEndpoint.java:678) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToHost(TcpEndpoint.java:608) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connect(TcpEndpoint.java:543) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager.connect(ConnectionManager.java:242) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager$ReqIterator.next(ConnectionManager.java:664) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicObjectEndpoint$1.next(BasicObjectEndpoint.java:370) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:708) ~[jsk-platform-2.2.1.jar:2.2.0]
Wrapped by: java.rmi.ConnectException: connection refused or timed out to BasicObjectEndpoint[65bf4513-5310-4fe4-af44-3fa956271998,TcpEndpoint[10.1.101.186:32817]]; nested exception is: 
	java.net.ConnectException: Connection timed out
	at net.jini.jeri.BasicInvocationHandler.wrapSafeIOException(BasicInvocationHandler.java:890) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:711) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethod(BasicInvocationHandler.java:659) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invoke(BasicInvocationHandler.java:528) ~[jsk-platform-2.2.1.jar:2.2.0]
	at com.sun.proxy.$Proxy466.createNewTransaction(Unknown Source) ~[na:na]
	at com.travellinck.infrastructure.jini.space.scheduling.impl.PublishLaterRequestHandler$2.call(PublishLaterRequestHandler.java:117) ~[approval-engine-components-1.1.10.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
INFO  00:40:32.111 c.t.s.c.adaptor.ClickatellAdaptor - Checking for expired ReplyIdReservations
ERROR 00:40:32.131 c.t.s.c.adaptor.ClickatellAdaptor - Failed to clean up expired ReplyIdReservations
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:293) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.makeConnection(Driver.java:393) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.connect(Driver.java:267) ~[postgresql-9.1-901.jdbc4.jar:na]
	at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_79]
	at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[na:1.7.0_79]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:98) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:324) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:319) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:138) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:685) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:215) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:542) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.4.1.v20121003-ad44345): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:602) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:186) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:278) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:304) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:282) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor.cleanupExpiredReplyIds(ClickatellAdaptor.java:595) ~[gsm-sms-adaptor-1.1.jar:na]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor$1.run(ClickatellAdaptor.java:1476) [gsm-sms-adaptor-1.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:40:40.002 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:41:05.911 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:41:29.567 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:41:54.557 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:42:20.053 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
INFO  00:42:32.147 c.t.s.c.adaptor.ClickatellAdaptor - Checking for expired ReplyIdReservations
ERROR 00:42:32.164 c.t.s.c.adaptor.ClickatellAdaptor - Failed to clean up expired ReplyIdReservations
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:293) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.makeConnection(Driver.java:393) ~[postgresql-9.1-901.jdbc4.jar:na]
	at org.postgresql.Driver.connect(Driver.java:267) ~[postgresql-9.1-901.jdbc4.jar:na]
	at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_79]
	at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[na:1.7.0_79]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:98) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:324) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:319) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:138) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:685) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:215) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:542) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
Wrapped by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.4.1.v20121003-ad44345): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
Error Code: 0
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:602) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:186) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:278) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:304) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:282) ~[eclipselink-2.4.1.jar:2.4.1.v20121003-ad44345]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor.cleanupExpiredReplyIds(ClickatellAdaptor.java:595) ~[gsm-sms-adaptor-1.1.jar:na]
	at com.travellinck.supplier.clickatell.adaptor.ClickatellAdaptor$1.run(ClickatellAdaptor.java:1476) [gsm-sms-adaptor-1.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:42:32.343 c.t.i.j.s.s.i.PublishLaterRequestHandler - Transaction failed, failed to process PublishLaterRequestEntry
java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_79]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_79]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_79]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToSocketAddress(TcpEndpoint.java:678) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connectToHost(TcpEndpoint.java:608) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.tcp.TcpEndpoint$ConnectionEndpointImpl.connect(TcpEndpoint.java:543) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager.connect(ConnectionManager.java:242) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.connection.ConnectionManager$ReqIterator.next(ConnectionManager.java:664) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicObjectEndpoint$1.next(BasicObjectEndpoint.java:370) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:708) ~[jsk-platform-2.2.1.jar:2.2.0]
Wrapped by: java.rmi.ConnectException: connection refused or timed out to BasicObjectEndpoint[65bf4513-5310-4fe4-af44-3fa956271998,TcpEndpoint[10.1.101.186:32817]]; nested exception is: 
	java.net.ConnectException: Connection timed out
	at net.jini.jeri.BasicInvocationHandler.wrapSafeIOException(BasicInvocationHandler.java:890) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:711) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethod(BasicInvocationHandler.java:659) ~[jsk-platform-2.2.1.jar:2.2.0]
	at net.jini.jeri.BasicInvocationHandler.invoke(BasicInvocationHandler.java:528) ~[jsk-platform-2.2.1.jar:2.2.0]
	at com.sun.proxy.$Proxy466.createNewTransaction(Unknown Source) ~[na:na]
	at com.travellinck.infrastructure.jini.space.scheduling.impl.PublishLaterRequestHandler$2.call(PublishLaterRequestHandler.java:117) ~[approval-engine-components-1.1.10.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
ERROR 00:42:43.709 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:43:10.642 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
ERROR 00:43:34.706 c.t.c.e.i.r.MailReceiverService - Non-permanent failure retrieving mail from box 'approval': javax.mail.AuthenticationFailedException: Logon failure: unknown user name or bad password.
